module DoorkeeperJp
  VERSION: String
  # See the writing guide of rbs: https://github.com/ruby/rbs#guides

  class Error < StandardError
  end

  def self.client: (?String? access_token) -> DoorkeeperJp::Client
end
